# Generated by Django 4.1.4 on 2022-12-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurgerPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toplist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgit.user')),
                ('burger_places', models.ManyToManyField(limit_choices_to={'id__lte': 5}, to='burgit.burgerplace')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='top_five',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='burgit.toplist'),
        ),
    ]
