# Generated by Django 4.1.4 on 2022-12-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgit', '0003_rename_top_five_user_top_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toplist',
            name='burger_places',
            field=models.ManyToManyField(to='burgit.burgerplace'),
        ),
    ]
