# Generated by Django 4.1.4 on 2022-12-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgit', '0006_alter_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='top_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='burgit.toplist'),
        ),
    ]
